version: "2"
linters:
  enable:
    - bodyclose # Checks whether HTTP response body is closed successfully.
    - goconst # Finds repeated strings that could be replaced by a constant.
    - gocyclo # Computes and checks the cyclomatic complexity of functions.
    - misspell # Finds commonly misspelled English words.
    - nakedret # Checks that functions with naked returns are not longer than a maximum size (can be zero).
    - revive # Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint.
    - tparallel # Detects inappropriate usage of t.Parallel() method in your Go test codes.
    - unconvert # Remove unnecessary type conversions.
    - unparam # Reports unused function parameters.
    - testifylint # Checks usage of github.com/stretchr/testify.
    - whitespace # Whitespace is a linter that checks for unnecessary newlines at the start and end of functions, if, for, etc.
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
