
final_space = true
version = 2
console_title_template = '{{ .Shell }} in {{ .Folder }}'


[palette]
main-bg = "#24283b"
terminal-red = "#f7768e"
pistachio-green = "#9ece6a"
terminal-green = "#73daca"
terminal-yellow = "#e0af68"
terminal-blue = "#7aa2f7"
celeste-blue = "#b4f9f8"
light-sky-blue = "#7dcfff"
terminal-white = "#c0caf5"
white-blue = "#a9b1d6"
blue-bell = "#9aa5ce"
pastal-grey = "#cfc9c2"
terminal-magenta = "#bb9af7"
blue-black = "#565f89"
terminal-black = "#414868"
t-background = "p:main-bg"
grey = "#6c6c6c"

[[blocks]]
	type = 'prompt'
	alignment = 'left'
	newline = true

	[[blocks.segments]]
		type = 'path'
		style = 'plain'
		background = 'transparent'
		foreground = 'p:terminal-blue'
		template = '{{ .Path }}'

		[blocks.segments.properties]
			style = 'full'

	[[blocks.segments]]
		type = 'git'
		style = 'plain'
		foreground = 'p:grey'
		background = 'transparent'
		template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0}}{{ end }} {{ if gt .Ahead 0 }}{{ end }}</>'

		[blocks.segments.properties]
			commit_icon = '@'
			fetch_status = true

[[blocks]]
	type = 'rprompt'
	overflow = 'hidden'

	[[blocks.segments]]
		type = 'executiontime'
		style = 'plain'
		foreground = 'p:terminal-yellow'
		background = 'transparent'
		template = '{{ .FormattedMs }}'


[[blocks]]
	type = 'prompt'
	alignment = 'left'
	newline = true
	
	[[blocks.segments]]
		type = 'text'
		style = 'plain'
		foreground_templates = [
			"{{if gt .Code 0}}p:terminal-red{{end}}",
			"{{if eq .Code 0}}p:terminal-magenta{{end}}",
		]
		background = 'transparent'
		template = '>'

[transient_prompt]
	foreground_templates = [
		"{{if gt .Code 0}}p:terminal-red{{end}}",
		"{{if eq .Code 0}}p:terminal-magenta{{end}}",
	]
	background = 'transparent'
	template = '> '

[secondary_prompt]
	foreground = 'p:terminal-magenta'
	background = 'transparent'
	template = '>> '
